#We need to deploy a Drupal application on Kubernetes cluster. The Nautilus application development team want to setup a fresh Drupal as they will do the installation on their own. Below you can find the requirements, they have shared with us. 1) Configure a persistent volume drupal-mysql-pv with hostPath = /drupal-mysql-data (/drupal-mysql-data directory already exists on the worker Node i.e jump host), 5Gi of storage and ReadWriteOnce access mode. 2) Configure one PersistentVolumeClaim named drupal-mysql-pvc with storage request of 3Gi and ReadWriteOnce access mode. 3) Create a deployment drupal-mysql with 1 replica, use mysql:5.7 image. Mount the claimed PVC at /var/lib/mysql. 4) Create a deployment drupal with 1 replica and use drupal:8.6 image. 4) Create a NodePort type service which should be named as drupal-service and nodePort should be 30095. 5) Create a service drupal-mysql-service to expose mysql deployment on port 3306. 6) Set rest of the configration for deployments, services, secrets etc as per your preferences. At the end you should be able to access the Drupal installation page by clicking on App button. Note: The kubectl on jump_host has been configured to work with the kubernetes cluster.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mysql-pv
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /drupal-mysql-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mysql-pvc
spec:
  resources:
    requests:
      storage: "3Gi"
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  template:
    metadata:
      labels:
        app: drupal-mysql
    spec:
      volumes:
        - name: drupal-volume
          persistentVolumeClaim:
            claimName: drupal-mysql-pvc
      containers:
      - name: drupal-mysql-container
        image: mysql:5.7
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: drupal-volume
        ports:
        - containerPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal-container
        image: drupal:8.6
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30095

---
apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
spec:
  selector:
    app: drupal-mysql
  ports:
  - port: 3306
    targetPort: 3306


