apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
data:
  php.ini: |
    variables_order: "EGPCS"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-wp
spec:
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      volumes:
        - name: php-ini
          configMap:
            name: php-config
      containers:
      - name: httpd-php-container
        image: webdevops/php-apache:alpine-3-php7
        resources: {}
        volumeMounts:
          - mountPath: /opt/docker/etc/php/php.ini
            name: php-ini
            subPath: php.ini
        ports:
        - containerPort: 80
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_ROOT_PASSWORD
                name: database
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_PASSWORD
                name: database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: MYSQL_USER
                name: database
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: MYSQL_DATABASE
                name: database
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                key: MYSQL_HOST
                name: database
      - name: mysql-container
        image: mysql:5.6
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_ROOT_PASSWORD
                name: database
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_PASSWORD
                name: database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: MYSQL_USER
                name: database
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: MYSQL_DATABASE
                name: database
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                key: MYSQL_HOST
                name: database
            resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: lamp-service
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
  - port: 80
    targetPort: 80
    nodePort: 3008

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: httpd
  ports:
  - port: 3306
    targetPort: 3306


