apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 8093
    targetPort: 8093
    nodePort: 30012

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {} 
    http {
      server {
        listen 8093;
        index index.html index.htm index.php;
        root  /var/www/html;
        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }


---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-phpfpm
  labels:
    app: nginx
spec:
  volumes:
    - name: shared-files
      emptyDir: {}
    - name: nginx-config-volume
      configMap:
        name: nginx-config
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
      - mountPath: /etc/nginx/nginx.conf
        name: nginx-config-volume
        subPath: nginx.conf
      - mountPath: /var/www/html
        name: shared-files
  - name: php-fpm-container
    image: php:7.2-fpm-alpine
    volumeMounts:
      - mountPath: /var/www/html
        name: shared-files
  
  



